const CollectionData = [
    {
        "id": 1,
        "thumb": "collection1.jpg",
        "title": "Fictional Character",
        "category": "cartoon",
        "date": "14",
        "hours": "23",
        "minute": "45",
        "second": "29",
        "bid": "17.15ETH",
        "author": "author1.jpg",
        "name": "David Beckham",
        "designation": "Creator",
        "wish": 2,
        "icon": "far fa-heart"
    },
    {
        "id": 2,
        "thumb": "collection2.jpg",
        "title": "Fictional Character",
        "category": "sports",
        "date": "12",
        "hours": "21",
        "minute": "40",
        "second": "21",
        "bid": "15.15ETH",
        "author": "author2.jpg",
        "name": "Lionel Messi",
        "designation": "Creator",
        "wish": 3,
        "icon": "far fa-heart"
    },
    {
        "id": 3,
        "thumb": "collection3.jpg",
        "title": "Fictional Character",
        "category": "music",
        "date": "16",
        "hours": "13",
        "minute": "25",
        "second": "24",
        "bid": "12.15ETH",
        "author": "author3.jpg",
        "name": "Nemar Jr.",
        "designation": "Creator",
        "wish": 4,
        "icon": "far fa-heart"
    },
    {
        "id": 4,
        "thumb": "collection4.jpg",
        "title": "Fictional Character",
        "category": "artworks",
        "date": "12",
        "hours": "14",
        "minute": "42",
        "second": "20",
        "bid": "14.15ETH",
        "author": "author4.jpg",
        "name": "Cristiano R.",
        "designation": "Creator",
        "wish": 6,
        "icon": "far fa-heart"
    },
    {
        "id": 5,
        "thumb": "collection5.jpg",
        "title": "Fictional Character",
        "category": "fashion",
        "date": "14",
        "hours": "23",
        "minute": "45",
        "second": "29",
        "bid": "17.15ETH",
        "author": "author1.jpg",
        "name": "David Beckham",
        "designation": "Creator",
        "wish": 2,
        "icon": "far fa-heart"
    },
    {
        "id": 6,
        "thumb": "collection6.jpg",
        "title": "Fictional Character",
        "category": "virtual",
        "date": "12",
        "hours": "21",
        "minute": "40",
        "second": "21",
        "bid": "15.15ETH",
        "author": "author2.jpg",
        "name": "Lionel Messi",
        "designation": "Creator",
        "wish": 3,
        "icon": "far fa-heart"
    },
    {
        "id": 7,
        "thumb": "collection7.jpg",
        "title": "Fictional Character",
        "category": "game",
        "date": "16",
        "hours": "13",
        "minute": "25",
        "second": "24",
        "bid": "12.15ETH",
        "author": "author3.jpg",
        "name": "Nemar Jr.",
        "designation": "Creator",
        "wish": 4,
        "icon": "far fa-heart"
    },
    {
        "id": 8,
        "thumb": "collection8.jpg",
        "title": "Fictional Character",
        "category": "collectibles",
        "date": "12",
        "hours": "14",
        "minute": "42",
        "second": "20",
        "bid": "14.15ETH",
        "author": "author4.jpg",
        "name": "Cristiano R.",
        "designation": "Creator",
        "wish": 6,
        "icon": "far fa-heart"
    }
]

export default CollectionData;